//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SundiresDeliverApp.Core.Database_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_COMCRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MS_COMCRE()
        {
            this.AD_MSITMCAT = new HashSet<AD_MSITMCAT>();
            this.AD_MSITMTYPE = new HashSet<AD_MSITMTYPE>();
            this.AD_MSITMUNIT = new HashSet<AD_MSITMUNIT>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string MachineID { get; set; }
        public string MachineIP { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string AboutUs { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string FAddress { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string EmailID { get; set; }
        public string GSTNo { get; set; }
        public string PANNo { get; set; }
        public string ContactPerson { get; set; }
        public string WebSite { get; set; }
        public string Logo { get; set; }
        public string Stamp { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AD_MSITMCAT> AD_MSITMCAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AD_MSITMTYPE> AD_MSITMTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AD_MSITMUNIT> AD_MSITMUNIT { get; set; }
    }
}
