//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SundiresDeliverApp.Core.Database_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SundriesMarketEntities : DbContext
    {
        public SundriesMarketEntities()
            : base("name=SundriesMarketEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
        

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<AD_MSITMCAT> AD_MSITMCAT { get; set; }
        public virtual DbSet<AD_MSITMTYPE> AD_MSITMTYPE { get; set; }
        public virtual DbSet<AD_MSITMUNIT> AD_MSITMUNIT { get; set; }
        public virtual DbSet<MS_COMCRE> MS_COMCRE { get; set; }
    }
}
